// Saya Muhamad Firdaus [2101995] mengerjakan
// soal TP 2 dalam mata kuliah DPBO
// untuk keberkahanNya maka saya tidak melakukan kecurangan 
// seperti yang telah dispesifikasikan. Aamiin.

import java.awt.CardLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Firdaus
 */
public class List extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    public List() {
        initComponents();
        
        // Criminal Table
        tbl_criminal.setModel(setTableCriminal());
        
        // Account Table
        tbl_account.setModel(setTableAccount());
    }

    // Data displayed as table
    public final DefaultTableModel setTableCriminal() {
        // Column
        Object[] column = {"ID", "Name", "Rewards"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        
        // Select database images
        String sql = "SELECT * FROM `images`";

        try {
            // Receive data
            PreparedStatement statement = DbConnection.configDB().prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                Object[] row = new Object[3];
                row[0] = rs.getString("id_criminal");
                row[1] = rs.getString("name");
                row[2] = rs.getString("reward");
                dataTabel.addRow(row);
           }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return dataTabel;
    }
    
    // Data displayed as table
    public final DefaultTableModel setTableAccount() {
        // Column
        Object[] column = {"User ID"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        
        // Select database Accountt
        String sql = "SELECT * FROM `Account`";

        try {
            // Receive data
            PreparedStatement statement = DbConnection.configDB().prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                Object[] row = new Object[3];
                row[0] = rs.getString("idAccount");
                dataTabel.addRow(row);
           }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return dataTabel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPan = new javax.swing.JPanel();
        Account = new javax.swing.JPanel();
        lbl_account = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_account = new javax.swing.JTable();
        Criminal = new javax.swing.JPanel();
        lbl_criminal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_criminal = new javax.swing.JTable();
        btn_account = new javax.swing.JButton();
        btn_criminal = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPan.setLayout(new java.awt.CardLayout());

        Account.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_account.setText("List Account");

        tbl_account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_account);

        javax.swing.GroupLayout AccountLayout = new javax.swing.GroupLayout(Account);
        Account.setLayout(AccountLayout);
        AccountLayout.setHorizontalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addGroup(AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_account))
                    .addGroup(AccountLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        AccountLayout.setVerticalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_account)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        mainPan.add(Account, "Account");

        Criminal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_criminal.setText("Criminal Data");

        tbl_criminal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_criminal);

        javax.swing.GroupLayout CriminalLayout = new javax.swing.GroupLayout(Criminal);
        Criminal.setLayout(CriminalLayout);
        CriminalLayout.setHorizontalGroup(
            CriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriminalLayout.createSequentialGroup()
                .addGroup(CriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriminalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_criminal))
                    .addGroup(CriminalLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        CriminalLayout.setVerticalGroup(
            CriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriminalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_criminal)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        mainPan.add(Criminal, "Criminal");

        btn_account.setText("Account");
        btn_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accountActionPerformed(evt);
            }
        });

        btn_criminal.setText("Criminal");
        btn_criminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criminalActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_account)
                        .addGap(183, 183, 183)
                        .addComponent(btn_criminal))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_account)
                    .addComponent(btn_criminal))
                .addGap(18, 18, 18)
                .addComponent(mainPan, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_criminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criminalActionPerformed
        // TODO add your handling code here:
        // Card Table Criminal
        CardLayout card = (CardLayout)mainPan.getLayout();
        card.show(mainPan, "Criminal");
    }//GEN-LAST:event_btn_criminalActionPerformed

    private void btn_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accountActionPerformed
        // TODO add your handling code here:
        // Card Table Account
        CardLayout card = (CardLayout)mainPan.getLayout();
        card.show(mainPan, "Account");
    }//GEN-LAST:event_btn_accountActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        // Close the current form
        String idAccount = UserAccount.accountId;
        this.setVisible(false);
        
        // Go back to previous form
        JPanelCard panelCard = new JPanelCard();
        panelCard.setAccountId(idAccount);
        panelCard.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JPanel Criminal;
    private javax.swing.JButton btn_account;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_criminal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_criminal;
    private javax.swing.JPanel mainPan;
    private javax.swing.JTable tbl_account;
    private javax.swing.JTable tbl_criminal;
    // End of variables declaration//GEN-END:variables
}
